name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up Conda
      uses: goanpeca/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
        environment-file: environment.yml  # Asegúrate de que el archivo esté en la raíz
        activate-environment: myenv

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda activate myenv

    - name: Run script
      run: python your_script.py
